### ISSUE TITLE
Auto forget configuration

### ISSUE THREAD

**Issue by LM1LC3N7** [cupcakearmy/autorestic#158]
**Is your feature request related to a problem? Please describe.**

I don't understand for sure in the doc if the forget part is done each time cron is triggered or if I need to manually execute it.

**Describe the solution you'd like**

A new config part in the yaml file to enable auto forget and prune according to the policy. This would allow cron to backup and remove old data every time it is triggered.

**Comment by cupcakearmy** [comment]
That sounds like a good idea to have

**Comment by JeWe37** [comment]
Mhmm couldn't this most simply be implemented by just running a forget(if configured) every time that the backup cron job is run? You do not really need more specific scheduling since you already can use the forget policies to configure how many snapshots to keep from what times. Would probably amount to a one-line fix.

**Comment by LM1LC3N7** [comment]
Yes that is what I did, but it would be convenient if it was included. It could work out of the box!

**Comment by LM1LC3N7** [comment]
Great, thanks a lot! 🎉

**Comment by cupcakearmy** [comment]
Docs btw, if anyone is wondering: https://autorestic.vercel.app/location/forget#automatically-forget-after-backup

**Comment by Coliinnn** [comment]
Updated link to the documentation:
